### PR TITLE
Morphing Code

### PR DESCRIPTION
**Pull request by ptrgags**
This is the entirety of the morph code I worked on during my time on this project. There's a README in the PFI_Morph directory explaining how it works.

I'm not sure what will happen with this repository, though I suppose that is up to Professor Breen and Professor Shokoufandeh to decide. 

In any case, this branch is at a stable point to merge into `master`. Whether it gets merged is up to you.

### CODE REVIEW

**Comment by ptrgags** [comment]
I don't know who's in charge of this repository now, but this branch should be merged at some point. It contains a stable build of everything I worked on during my time working on this project back in the spring.

I'm just commenting here to make sure someone sees this branch.

**Comment by gnitsua** [comment]
Hey, is there any chance you could check best practices for .gitignore-ing this type of project? It seems like there are a lot of files that are binary/probably shouldn't be committed. Maybe I'm wrong

**Comment by ptrgags** [comment]
Oh my, I see what you mean. It looks like Hollis did add a `.gitignore`, but binary files got checked in anyway. Sometime this week I'll go through and remove such files. 

Those files were a different section of the code from what I worked on (I only worked in the `PFI_Morph` directory) so I didn't notice them until now.

**Comment by gnitsua** [comment]
No problem, but I think you might have an easier time cleaning this up than me.
________________________________

**Comment by ptrgags** [comment]
I removed old build binary files that were somehow checked in.

I'm not sure what to do with the `*.xcodeproj/` directories. I've never worked with Swift, so I do not know if they are important IDE project files or just user-specific customizations. I do not have a Mac so I can't experiment with it.

@gnitsua would you like me to keep these files around just to be safe, or should I get rid of IDE files that are not source code?

**Comment by gnitsua** [comment]
What about this? https://github.com/github/gitignore/blob/master/Swift.gitignore

**Comment by ptrgags** [comment]
@gnitsua are any further changes needed or can this be merged?

**Comment by gnitsua** [comment]
Looks reasonable I guess, thanks for helping on this

**Pull request merged**
